### ISSUE TITLE
More flexible built information embedding

### ISSUE THREAD

**Issue by redmie** [PyO3/pyo3-built#26]
I was not satisfied with how rigid this macro was.
I wanted to add git information in the dictionary, but not add crate dependencies versions information.

This led me to write PR #25 which keeps the macro default comportment by default but allow finer control of what should be in the build dict when needed.

Please advise!

**Comment by althonos** [comment]
Yes, sorry about the delay, I haven't had much time to do any review here for work-related reasons. I think your proposed enhancement is great and it will definitely get merged, it's just a matter of _when_ :wink:
